### ISSUE TITLE
Project uses GPL 3 code but doesn't state the license

### ISSUE THREAD

**Issue by tgvaughan** [NicoNeureiter/contactrees#5]
Hi Nico :)

Well done on this package and the publication!  I just noticed however that you haven't explicitly noted the license under which this package is released.  Given that it directly uses GPL 3 code from Bacter, I believe contacTrees should be similarly licensed.

Thank you!

Tim

**Comment by rbouckaert** [comment]
Thanks for pointing that out TIm! We should have added the license much earlier but b46758579038fe3a1c6f389fad54409aecb8c4d0 has just done that.

**Comment by tgvaughan** [comment]
Thanks Remco.

**Comment by NicoNeureiter** [comment]
True, this should have been in there earlier. Thanks for pointing it out Tim!
